### ISSUE TITLE
Show date in listening history

### ISSUE THREAD

**Issue by Joedmin** [woheller69/whoBIRD#26]
Currently the listening history list shows only the time each bird (or human vocals) were matched by the model but not the date.

I would like to know when I heard some bird because I believe it would add more clarity to each matches.

If you don't want to show the date for each bird, it might be better to separate the list by dates with a horizontal line with the corresponding date.

**Comment by woheller69** [comment]
I don't want a date in every item as it requires a lot of space. 
Having a separator is complex, because RecyclerView does not support it. So it would require a lot of code.
Most people will simply clear this list every day, so it is not important for them.
If the list is exported, you have the full timestamp (seconds since 1970) and can do further evaluation, e.g in Excel.

**Comment by woheller69** [comment]
a simple solution might be to add date/time below the name in the image. So you will see it when the item is selected and the image is shown

**Comment by woheller69** [comment]
You can try this version:
Uninstall
Remove .zip and install
[app-release.apk.zip](https://github.com/woheller69/whoBIRD/files/14720243/app-release.apk.zip)

**Comment by woheller69** [comment]
[app-release.apk.zip](https://github.com/woheller69/whoBIRD/files/14720537/app-release.apk.zip)

**Comment by woheller69** [comment]
Now also with a header.
[app-release.apk.zip](https://github.com/woheller69/whoBIRD/files/14721493/app-release.apk.zip)

**Comment by Joedmin** [comment]
Thank you very much! This is exactly as I imagined it!
